name: build & deploy to vercel

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PRODUCTION: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ check out code
        uses: actions/checkout@master
        with:
          submodules: true

      - name: 🖼️ restore cached images
        id: cache-images-restore
        uses: actions/cache/restore@v4
        with:
          path: .astro
          key: Images-${{ runner.os }}

      - name: ➕ update package lists
        run: sudo apt-get update

      - name: ➕ install musescore
        run: sudo apt-get install -y musescore

      - name: ➕ install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: ➕ install node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: ➕ install node dependencies
        run: pnpm install --no-frozen-lockfile

      - name: ➕ install vercel cli
        run: pnpm install --global vercel

      - name: 🔺 pull vercel environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: ⚙️ build
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          FLICKR_API_KEY: ${{ secrets.FLICKR_API_KEY }}

      - name: 🔺 deploy to vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: 🖼️ check if image cache exists for current branch
        id: actions-cache-list
        env:
          GH_TOKEN: ${{ github.token }}
        run: echo "RESULT=$(gh actions-cache list --branch ${{ github.ref }} --key Images-)" >> $GITHUB_OUTPUT

      - name: 🖼️ clear existing image cache
        if: ${{ steps.actions-cache-list.outputs.RESULT != '' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh actions-cache delete ${{ steps.cache-images-restore.outputs.cache-primary-key }} --branch ${{ github.ref }} --confirm

      - name: 🖼️ cache images
        uses: actions/cache/save@v4
        with:
          path: .astro
          key: ${{ steps.cache-images-restore.outputs.cache-primary-key }}
